services:
  database:
    image: mysql:8.0.29
    environment:
      - MYSQL_DATABASE=EXAMPLE_JPA
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /home/rafael/Documentos/workspace/mysql/volume:/var/lib/mysql
